name: TrustLens Security Pipeline

# trigger when developer pushesh the code in main branch or developer opens pull request proposing changes
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# create temporary new Linux Server to handle the scan
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:

      # Downloads source code in Ubuntu server
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # installing the scanners
      - name: Install Semgrep & Checkov
        run: pip install semgrep checkov

      - name: Install Trivy
        run: curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      # it triggers the python script to scan the downloaded code collect different outputs, normalize them and bundle them into findings.json
      - name: Run TrustLens Orchestrator
        run: python trustlens/main.py . findings.json

      # The Database Connection
      - name: Install DB Dependencies
        run: pip install psycopg2-binary sqlalchemy  # Adjust if your script uses specific drivers

      - name: Ingest Findings to Cloud Database
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python trustlens/ingest_findings.py findings.json

      - name: Save Findings Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: trustlens-security-report
          path: findings.json