name: TrustLens Security Pipeline

# trigger when developer pushes the code in main branch or developer opens pull request proposing changes
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# create temporary new Linux Server to handle the scan
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:

      # Downloads source code in Ubuntu server
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # installing the scanners
      - name: Install Semgrep & Checkov
        run: pip install semgrep checkov

      - name: Install Trivy
        run: curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      # 1. Install DB Dependencies FIRST so python can import psycopg2 safely
      - name: Install DB Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary sqlalchemy pydantic

      # 2. Now run the python script to scan, normalize, and ingest
      - name: Run TrustLens Orchestrator & Ingest
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          cd trustlens
          python main.py .. findings.json

      # 3. Save Artifact report as a backup
      - name: Save Findings Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: trustlens-security-report
          path: trustlens/findings.json